name: Monitores de Ingressos
on:
  schedule:
    - cron: '*/10 * * * *' # Roda a cada 10 minutos
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install puppeteer axios puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run BTS Monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node monitor.js

      - name: Run Harry Styles Monitor
        if: false # [STAND BY] Mude de volta para always() para reativar
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node monitor_harry.js