name: Monitor BTS Tickets
on:
  schedule:
    - cron: '*/10 * * * *' # Roda a cada 10 minutos
  workflow_dispatch: # Permite rodar manualmente no painel do GitHub

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer axios

      - name: Run Monitor
        env:
          # Buscando valores das configurações protegidas do repositório
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node monitor.js